lint.ignore = ["F405", "E402", "E501", "F403"]
lint.extend-select = ["E501", "PLR0915", "T20"]
line-length = 120
exclude = ["llm/types/*", "llm/__init__.py", "llm/proxy/example_config_yaml/*", "tests/*"]


[lint.per-file-ignores]
"llm/main.py" = ["F401"]
"llm/utils.py" = ["F401"]
"llm/proxy/proxy_server.py" = ["F401"]
"llm/caching/__init__.py" = ["F401"]
"llm/llms/anthropic/chat/__init__.py" = ["F401"]
"llm/llms/azure_ai/embed/__init__.py" = ["F401"]
"llm/llms/azure_ai/rerank/__init__.py" = ["F401"]
"llm/llms/bedrock/chat/__init__.py" = ["F401"]