blank_issues_enabled: true
contact_links:
  - name: Schedule Demo
    url: https://calendly.com/d/4mp-gd3-k5k/llm-1-1-onboarding-chat
    about: Speak directly with the team, to discuss issues, share feedback, or explore improvements for LLM
  - name: Discord
    url: https://discord.com/invite/XthHQQj
    about: Join 250+ LLM community members!
