fullnameOverride: ""
# Disable database deployment and configuration
db:
  deployStandalone: false
  useExisting: false

# Test environment variables
envVars:
  DD_ENV: "dev_helm"
  DD_SERVICE: "llm"
  USE_DDTRACE: "true"

# Disable migration job since we're not using a database
migrationJob:
  enabled: false