name: Build, Publish LLM Docker Image
on:
 workflow_dispatch:
   inputs:
     tag:
       description: "The tag version you want to build"
     release_type:
       description: "The release type you want to build. Can be 'latest', 'stable', 'dev'"
       type: string
       default: "latest"
     commit_hash:
       description: "Commit hash"
       required: true
 push:
   branches: [main]
   tags: ['v*']
env:
 REGISTRY: ghcr.io
 IMAGE_NAME: ${{ github.repository }}
 CHART_NAME: llm-helm
jobs:
 set-metadata:
   runs-on: ubuntu-latest
   outputs:
     commit_hash: ${{ steps.set-values.outputs.commit_hash }}
     tag: ${{ steps.set-values.outputs.tag }}
     release_type: ${{ steps.set-values.outputs.release_type }}
   steps:
     - id: set-values
       run: |
         if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
           echo "commit_hash=${{ github.event.inputs.commit_hash }}" >> $GITHUB_OUTPUT
           echo "tag=${{ github.event.inputs.tag || 'latest' }}" >> $GITHUB_OUTPUT
           echo "release_type=${{ github.event.inputs.release_type || 'latest' }}" >> $GITHUB_OUTPUT
         elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
           echo "commit_hash=${{ github.sha }}" >> $GITHUB_OUTPUT
           echo "tag=latest" >> $GITHUB_OUTPUT
           echo "release_type=latest" >> $GITHUB_OUTPUT
         elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
           echo "commit_hash=${{ github.sha }}" >> $GITHUB_OUTPUT
           echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
           echo "release_type=stable" >> $GITHUB_OUTPUT
         fi
 docker-hub-deploy:
   needs: set-metadata
   if: github.repository == 'hanzoai/llm'
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         ref: ${{ needs.set-metadata.outputs.commit_hash }}
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
       with:
         driver: docker-container
         buildkitd-flags: --debug
     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build and push
       uses: docker/build-push-action@v5
       with:
         context: .
         push: true
         tags: llm/llm:${{ needs.set-metadata.outputs.tag }}
 build-and-push-image:
   needs: set-metadata
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
       with:
         ref: ${{ needs.set-metadata.outputs.commit_hash }}
     - name: Log in to the Container registry
       uses: docker/login-action@v3
       with:
         registry: ${{ env.REGISTRY }}
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
       with:
         driver: docker-container
         buildkitd-flags: --debug
     - name: Build and push Docker image
       uses: docker/build-push-action@v5
       with:
         context: .
         push: true
         tags: |
           ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.set-metadata.outputs.tag }}
           ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.set-metadata.outputs.release_type }}
         platforms: linux/amd64,linux/arm64
